/***************************************************************
 * Copyright (C) 2018
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ***************************************************************/

/* FILE NAME   : MTHDEF.H
 * PURPOSE     : WinAPI animation system.
 *               Math base defenitions.
 * PROGRAMMER  : DT6.
 * LAST UPDATE : 15.07.2018.
 * NOTE        : None.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum
 */

#ifndef __MTHDEF_H_
#define __MTHDEF_H_

#include <cmath>
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <istream>
#include <ostream>

#include <commondf.h>

typedef double DBL;
typedef float FLT;

namespace mth
{
  const long double PI = 3.141592653589793; // PI constant
}

#endif // __MTHDEF_H_

